NUMPY

In [1]:
import numpy as np
# Numpy --> Numeric Python
# ndarray --> n dimensional array

In [4]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
print(type(np1))
print(np1.shape) # length of ndarray

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)


In [ ]:
# --- arrange func --- #
np2 = np.arange(9) # make list from 0 --> l-1
print(np2)

In [5]:
# --- zero func --- #
np4 = np.zeros(10) # make a list of 0 of size n
print(np4)
#-----random numbers ------#
random_int = np.random.randint(1, 10, size=5)
print(random_int)
# multi-dimensional #
np5 = np.ones(3) # --> creates 2D array with 5 zero in each dim
print(np5)
# --- full func --- #
np6 = np.full((10),3)
print(np6)
np7 = np.full((3,5),9)
print(np7)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2 4 5 1 3]
[1. 1. 1.]
[3 3 3 3 3 3 3 3 3 3]
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [ ]:
# --- slicing --- #
li = [1, 2, 3, 4, 5, 6, 7, 8, 9]
n = np.array(li)

print(n[1:4])  # --> 2, 3, 4
print(n[:4])  # --> 1, 2, 3, 4 (start from 0)
print(n[4:])  # --> 5, 6, 7, 8, 9 (end at last index)
print(n[0:9:2])

[2 3 4]
[1 2 3 4]
[5 6 7 8 9]
[1 3 5 7 9]


In [ ]:
#------ Maths Opeartion -----#
l = [1, 4, 9, 16, 25, 36, 49, 64, 81]
l2 = [-1, -4, -9, -16, -25, -36, -49, 64, 81]
n = np.array(l)
n2 = np.array(l2)
print(n)

# Square root of each element #
print(np.sqrt(n))

# Absolute value of each element #
print(np.absolute(n2))  # --> returns positive value

# Min/Max of each element #
print(np.min(n))
print(np.max(n))

[ 1  4  9 16 25 36 49 64 81]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 1  4  9 16 25 36 49 64 81]
1
81
